apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources: {}
status: {}
